POST http://localhost:8080/events
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTk1OTEyNjgsInVzZXJJZCI6MX0.otQ5Eid0vzYn3J242pDsJ7cFTZqfMmIxUpfHxKB4aR0"

{
    "name": "Test Event",
    "description": "A Test Event",
    "location": "A Test Location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}