DELETE  http://localhost:8080/events/1
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTk1OTEyNjgsInVzZXJJZCI6MX0.otQ5Eid0vzYn3J242pDsJ7cFTZqfMmIxUpfHxKB4aR0"